; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.10+4-LPC on Mon Jan 04 2021 14:32:28 GMT+0800 (中国标准时间)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


