; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.10+4-LPC on Mon Jan 04 2021 14:32:33 GMT+0800 (中国标准时间)
; Wait for set temperatures to be reached
M116 P0

