; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC on Fri Jan 15 2021 14:50:04 GMT+0800 (中国标准时间)
; Wait for set temperatures to be reached
M116 P0

